### ISSUE TITLE
Addtempo command messing up with playback state (bach.score)

### ISSUE THREAD

**Issue by arthur-parmentier** [bachfamily/bach#1]
Hello!

When send "cleartempi, addtempo <some_number>" to Bach.score while it is playing (in my case, in a loop), the following behavior occurs:

1) the playback stops for a while (several seconds)
2) the tempo indication is added correctly
3) after a moment, the playback starts again.

The behavior that I would expect is that the playback does not stop when sending a new addtempo command, so that I am able to control the tempo in real time.

**Comment by danieleghisi** [comment]
Adding a tempo has a large impact on the structures of the score and on the
graphic display (think at what happens if you had different tempi in
different voices!), many things are recomputed so it is not a good strategy
to do that in real-time.

You may want to use a setclock object in multiplicative mode instead: in
this way you have a smooth tempo control. See the "clock" message.

Hope this helps
Daniele

PS. in general, we prefer that questions like this are posted on the forum
of our website (www.bachproject.net/forum)

Il Mer 6 Mag 2020, 07:40 Arthur Parmentier <notifications@github.com> ha
scritto:

**Comment by arthur-parmentier** [comment]
Thanks; I will head to the forum instead for future questions!
